#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

# iterate through arguments
while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift # shift arguments (delete the first one)
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "------------- dev-env -------------"

copy_dir() {
  from=$1
  to=$2

  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from)

  execute rm $to/$name
  execute cp $from $to/$name
}

copy_dir env/.config $XDG_CONFIG_HOME
copy_dir env/.local $HOME/.local

copy_file env/.zsh_profile $HOME
copy_file env/.zshrc $HOME
copy_file env/.ready-tmux $HOME
#copy_file env/.xprofile $HOME/.xprofile
copy_file dev-env $HOME/.local/scripts
