#!/usr/bin/env bash

session=$(find ~ ~/personal ~/work -mindepth 1 -type d | fzf)
if [[ -z "$session" ]]; then
  exit
fi
session_name=$(basename "$session" | tr :,. _)

switch_to() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t $session_name
  else
    tmux switch-client -t $session_name
  fi
}

if tmux has-session -t="$session_name" 2> /dev/null; then
  switch_to
  exit 0
fi

tmux new-session -ds $session_name -c $session
switch_to
tmux send-keys -t $session_name "ready-tmux" 
